# environment.yml
name: disaster-alerts
channels:
  - conda-forge
dependencies:
  - python>=3.11
  - pydantic
  - pyyaml
  - requests
  - pytest
  - shapely 
  - folium
  - pip
  - pip:
      - yagmail
