earthquake:
  min_magnitude: 6.0
  max_depth_km: 700

weather:
  include_events:
    - Flood Warning
    - Hurricane
    - Storm Warning
  exclude_events:
    - Special Weather Statement
    # - Hazardous Weather Outlook
