earthquake:
  min_magnitude: 4.0
  max_depth_km: 700

weather:
  include_events:
    - Flood Warning
    - Hurricane
  exclude_events:
    - Special Weather Statement
    # - Hazardous Weather Outlook
